<div class="qdC news-content bor-wrap">
        <p></p><h1>CHÍNH SÁCH BẢO MẬT</h1><p></p>
        
        <div class="qdinhTop">
            <p><strong>DcbLand.com</strong> cam kết bảo vệ các thông tin riêng tư trực tuyến của bạn. Xin hãy đọc chính sách sau đây để hiểu cách chúng tôi xử lý các thông tin cá nhân của bạn khi bạn sử dụng đầy đủ website <strong>DcbLand.com</strong>. Việc sử dụng website <strong>DcbLand.com</strong> được hiểu là bạn chính thức đồng ý với các chính sách và việc thực hiện chúng được mô tả trong Chính sách này. Chính sách này có thể thay đổi theo thời gian nên bạn hãy kiểm tra lại theo định kỳ.</p>
            <p>Các site của chúng tôi chứa các liên kết tới các site khác mà chúng tôi không kiểm soát. DiaOcOnline Corp, công ty sở hữu và điều hành <strong>DcbLand.com</strong>, không chịu trách nhiệm về các chính sách bảo mật hoặc việc thực hiện chúng của các site mà bạn kết nối tới từ website <strong>DcbLand.com</strong>. Chúng tôi khuyến khích bạn xem xét các chính sách bảo mật thông tin của các site khác đó để có thể hiểu cách thức họ thu thập, sử dụng và chia sẻ thông tin của bạn. Chính sách Bảo mật này chỉ áp dụng cho các thông tin mà chúng tôi thu thập trên một website <strong>DcbLand.com</strong> và không áp dụng cho thông tin mà chúng tôi thu thập được theo cách khác.</p>
        </div>

        <div class="qdinhCon">
            <p><strong>Chính sách này sẽ cho bạn biết:</strong></p>
            <p class="font1">
                1. Các thông tin có thể nhận dạng cá nhân nào được thu thập từ bạn</p>
            <p><strong>DcbLand.com</strong> thu thập thông tin theo một số cách từ các mục khác nhau trên website của mình</p>
            <p>Một số thông tin cá nhân được tập hợp lại khi bạn đăng ký. Trong khi đăng ký, chúng tôi hỏi tên và địa chỉ email của bạn. Hệ thống cũng có thể hỏi địa chỉ đường phố, thành phố, quốc gia, số điện thoại, thông tin thanh toán và địa chỉ máy (URL) của website của bạn, mặc dù chỉ những trường được đánh dấu sao * trên phần đăng ký mới là thông tin bắt buộc. <strong>DcbLand.com</strong> cũng thu thập hoặc có thể thu thập thông tin nhân khẩu học không chỉ từ riêng bạn như tuổi tác, ưu tiên, giới tính, các mối quan tâm và sở thích. Đôi khi chúng tôi thu thập hoặc có thể thu thập một kết hợp của hai kiểu thông tin. Ngay khi bạn đăng ký, bạn không còn vô danh với <strong>DcbLand.com</strong> nữa, bạn có tên truy cập và có thể khai thác đầy đủ các sản phẩm/dịch vụ của website <strong>DcbLand.com</strong>.</p>
            <p>Ngoài thông tin đăng ký, đôi khi chúng tôi có thể hỏi bạn thông tin cá nhân bao gồm (nhưng không hạn chế) khi bạn đặt đăng quảng cáo hoặc khai thác các tính năng khác của website <strong>DcbLand.com</strong>. Nếu bạn liên lạc với chúng tôi, chúng tôi có thể giữ một bản ghi nhớ về sự liên lạc này. Mỗi trang trong phạm vi website <strong>DcbLand.com</strong> đều có đường dẫn tới Chính sách Bảo mật này.</p>
            <p class="font1">2. Cookies là gì và cách chúng được sử dụng</p>
            <p>Là một phần của việc đưa ra và cung cấp các dịch vụ cá nhân và theo yêu cầu khách hàng, website <strong>DcbLand.com</strong> có thể dùng các cookie để lưu và đôi khi theo dõi thông tin về bạn. Cookie là một lượng nhỏ dữ liệu được gửi tới trình duyệt của bạn từ máy chủ web và được lưu trên đĩa cứng máy tính của bạn. Một vài tính năng của website <strong>DcbLand.com</strong> đòi hỏi bạn chấp nhận các cookie mới có thể sử dụng được. (xem mục “Bạn có những lựa chọn nào khi thu thập, sử dụng và phân phối thông tin của bạn” để có thông tin chi tiết hơn về các cookie).</p>
            <p>Nói chung, chúng tôi dùng các cookie cho các mục đích sau đây:</p>
            <p>(1) Nhận dạng và gắn nhãn cho tất cả các công việc “mới” từ lần cuối cùng của bạn ghé thăm website</p>
            <p>(2) Lưu theo yêu cầu hoặc vĩnh viễn tên truy cập và mật khẩu lên máy của bạn để bạn không phải nhập lại mỗi lần ghé thăm website của chúng tôi</p>
            <p>(3) Cho phép bạn “kiểm tra danh sách” các công việc mà bạn muốn đánh dấu để giữ lại và xem sau này</p>
            <p>Các mạng quảng cáo của các công ty đăng việc trên website <strong>DcbLand.com</strong> cũng có thể dùng các cookie của riêng họ</p>
            <p><strong>DcbLand.com</strong> cũng sẽ tập hợp và có thể tập hợp thông tin nào đó về việc sử dụng website <strong>DcbLand.com</strong> của bạn, chẳng hạn những khu vực bạn ghé thăm và những dịch vụ bạn truy nhập. Ngoài ra, <strong>DcbLand.com</strong> cũng có thể thu thập những thông tin về phần cứng, phần mềm trên máy tính của bạn. Thông tin này có thể bao gồm những không hạn chế địa chỉ IP, kiểu trình duyệt, tên miền, các mục bạn truy nhập và các địa chỉ website tham chiếu.</p>
            <p class="font1">3. Thông tin của bạn được sử dụng như thế nào?</p>
            <p>Chúng tôi dùng thông tin tập hợp được trên một website của Chocophieu, dù đó là thông tin cá nhân, đều nhằm mục đích điều hành và cải tiến website <strong>DcbLand.com</strong>, tăng cường tiện ích cho người sử dụng và phân phối các sản phẩm và dịch vụ của chúng tôi.</p>
            <p>Chúng tôi cũng có thể dùng thông tin thu thập được để thông báo cho bạn về những sản phẩm và dịch vụ do <strong>DcbLand.com</strong> hay các công ty đối tác cung cấp, hoặc để xin ý kiến của bạn về các sản phẩm và dịch vụ hiện tại hay những sản phẩm và dịch vụ tiềm năng mới.</p>
            <p>Chúng tôi cũng có thể dùng thông tin liên lạc của bạn để gửi cho bạn email hoặc các thông báo khác về những cập nhật tại website của <strong>DcbLand.com</strong>. Nội dung và tần suất của những thông báo này sẽ thay đổi tuỳ thuộc vào thông tin mà chúng tôi có về bạn. Ngoài ra, vào lúc đăng ký, bạn có quyền lựa chọn nhận những thông tin, thông báo và các chương trình khuyến mãi bao gồm nhưng không hạn chế các bản tin miễn phí từ <strong>DcbLand.com</strong> liên quan đến những chủ đề mà bạn có thể đặc biệt quan tâm.</p>

            <p>Chúng tôi có một khu vực để bạn có thể liên lạc với chúng tôi. Bất kỳ phản hồi nào bạn gửi đến cho chúng tôi sẽ trở thành tài sản của chúng tôi và chúng tôi có thể dùng phản hồi đó (chẳng hạn các câu chuyện thành công) cho các mục đích tiếp thị, hoặc liên hệ với bạn để có thêm thông tin</p>
            <p class="font1">4. Thông tin của bạn có thể chia sẻ với ai?</p>
            <p>Chúng tôi không tiết lộ cho bên thứ ba thông tin cá nhân của bạn, cũng như thông tin cá nhân, hoặc thông tin về việc sử dụng website <strong>DcbLand.com</strong> của bạn (chẳng hạn các khu vực bạn ghé thăm, hay các dịch vụ mà bạn truy cập), trừ trường hợp sau đây.</p>
            <p>Chúng tôi có thể để lộ thông tin như vậy cho các nhóm thứ ba nếu bạn đồng ý.</p>
            <p>Chúng tôi có thể tiết lộ thông tin như vậy cho các công ty và cá nhân mà chúng tôi thuê để thay mặt chúng tôi thực hiện các chức năng của công ty. Ví dụ, việc lưu giữ các máy chủ web, phân tích dữ liệu, cung cấp các trợ giúp về marketing, xử lý thẻ tín dụng hoặc các hình thức thanh toán khác, và dịch vụ cho khách hàng. Những công ty và cá nhân này sẽ truy cập tới thông tin cá nhân của bạn khi cần để thực hiện các chức năng của họ, nhưng không chia sẻ thông tin đó với bất kỳ bên thứ ba nào khác.  </p>
            <p>Chúng tôi có thể tiết lộ thông tin như vậy nếu có yêu cầu pháp lý, hay từ một cơ quan chính phủ hoặc nếu chúng tôi tin rằng hành động đó là cần thiết nhằm: 
            <br>(a) tuân theo các yêu cầu pháp lý hoặc chiếu theo quy trình của luật pháp; 
            <br>(b) bảo vệ các quyền hay tài sản của DiaOcOnline Corp hoặc các công ty đối tác; 
            <br>(c) ngăn chặn tội phạm hoặc bảo vệ an ninh quốc gia; hoặc 
            <br>(d) bảo vệ an toàn cá nhân của những người sử dụng hay công chúng.</p>
            <p>Chúng tôi có thể tiết lộ và chuyển thông tin như vậy tới một nhóm thứ ba, đối tượng mua lại toàn bộ hay phần lớn công việc kinh doanh của công ty DiaOcOnline Corp bằng cách liên kết, hợp nhất hoặc mua toàn bộ hay phần lớn các tài sản của chúng tôi. Ngoài ra, trong tình huống DiaOcOnline Corp trở thành đối tượng của một vụ khởi kiện phá sản, dù tự nguyện hay miễn cưỡng, thì DiaOcOnline Corp hay người được uỷ thác có thể bán, cho phép hoặc tiết lộ thông tin như vậy theo cách khác trong quá trình chuyển giao được toà án về phá sản đồng ý.</p>
           
        </div>
            
    </div>